### ISSUE TITLE
Adding support for newer versions of JDK.

### ISSUE THREAD

**Issue by rchomczyk** [OkaeriPoland/okaeri-persistence#1]
It would be great, if okaeri-persistence gets an update for modules, because right now projects using this library cannot run on JDK 16 (without using --add-exports java.base/sun.reflect.generics.reflectiveObjects=ALL-UNNAMED option)

**Comment by sandrwich** [comment]
Can you provide specific stacktraces or any additional information? It is possible the issue described is not related directly to the core library, but rather its repository proxies abstraction.

**Comment by rchomczyk** [comment]
Here is the stacktrace:
```txt
[00:02:47] [Server thread/ERROR]: Error occurred while enabling SapphireCore v1.0.0 (Is it up to date?)
java.lang.IllegalAccessError: class dev.shitzuu.rosesapphire.core.platform.persistence.repository.RepositoryDeclaration (in unnamed module @0x2eb23aae) cannot access class sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl (in module java.base) because module java.base does not export sun.reflect.generics.reflectiveObjects to unnamed module @0x2eb23aae
	at dev.shitzuu.rosesapphire.core.platform.persistence.repository.RepositoryDeclaration.of(RepositoryDeclaration.java:31) ~[?:?]
	at dev.shitzuu.rosesapphire.core.platform.platform.bukkit.BukkitComponentCreator.makeObject(BukkitComponentCreator.java:149) ~[?:?]
	at dev.shitzuu.rosesapphire.core.platform.platform.core.component.manifest.BeanManifest.update(BeanManifest.java:200) ~[?:?]
	at dev.shitzuu.rosesapphire.core.platform.platform.core.component.manifest.BeanManifest.updateAllDependencies(BeanManifest.java:213) ~[?:?]
	at dev.shitzuu.rosesapphire.core.platform.platform.core.component.manifest.BeanManifest.update(BeanManifest.java:207) ~[?:?]
	at dev.shitzuu.rosesapphire.core.platform.platform.core.component.manifest.BeanManifest.execute(BeanManifest.java:325) ~[?:?]
	at dev.shitzuu.rosesapphire.core.platform.platform.bukkit.OkaeriBukkitPlugin.onEnable(OkaeriBukkitPlugin.java:271) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Airplane-10]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Airplane-10]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Airplane-10]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Airplane-10]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Airplane-10]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:595) ~[patched_1.16.5.jar:git-Airplane-10]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:301) ~[patched_1.16.5.jar:git-Airplane-10]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1071) ~[patched_1.16.5.jar:git-Airplane-10]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-Airplane-10]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```
